// Top 500 Mixed Indian and US Stocks for Watchlist Analysis
export const TOP_500_STOCKS = {
    // US Stocks - Top 250 by market cap and trading volume
    US: [
        // // Technology
        // "AAPL", "MSFT", "GOOGL", "GOOG", "AMZN", "TSLA", "META", "NVDA", "ORCL", "CRM",
        // "ADBE", "NFLX", "INTC", "CSCO", "IBM", "QCOM", "TXN", "AVGO", "AMAT", "LRCX",
        // "KLAC", "MRVL", "SNPS", "CDNS", "FTNT", "PANW", "CRWD", "ZS", "OKTA", "DDOG",

        // // Financial Services
        // "BRK.A", "BRK.B", "JPM", "BAC", "WFC", "GS", "MS", "C", "AXP", "BLK",
        // "SCHW", "USB", "PNC", "TFC", "COF", "DFS", "SYF", "PYPL", "V", "MA",

        // // Healthcare & Pharma
        // "JNJ", "PFE", "UNH", "ABBV", "MRK", "TMO", "ABT", "MDT", "ISRG", "DHR",
        // "BMY", "AMGN", "GILD", "VRTX", "REGN", "BIIB", "ILMN", "MRNA", "BNTX", "ZTS",

        // // Consumer & Retail
        // "HD", "MCD", "NKE", "SBUX", "LOW", "TGT", "WMT",
        // "COST", "KO", "PEP", "PG", "UL", "CL", "KMB", "GIS", "K", "CPB",

        // // Industrial & Manufacturing
        // "BA", "CAT", "DE", "MMM", "GE", "HON", "UPS", "FDX", "LMT", "RTX",
        // "NOC", "LHX", "GD", "TDG", "CTAS", "EMR", "ETN", "ITW", "CMI", "PCAR",

        // // Energy & Utilities
        // "XOM", "CVX", "COP", "EOG", "SLB", "MPC", "VLO", "PSX", "KMI", "OKE",
        // "WMB", "EPD", "ET", "MPLX", "NEE", "SO", "DUK", "AEP", "EXC", "XEL",

        // // Materials & Chemicals
        // "LIN", "APD", "ECL", "SHW", "DD", "DOW", "LYB", "CF", "MOS", "FMC",
        // "ALB", "VMC", "MLM", "EMN", "PPG", "RPM", "CC", "PKG", "IP", "WRK",

        // // REITs & Real Estate
        // "AMT", "CCI", "EQIX", "PLD", "WELL", "PSA", "EXR", "AVB", "EQR", "MAA",
        // "UDR", "CPT", "ESS", "AIV", "BXP", "VTR", "PEAK", "O", "STOR", "WPC",

        // // Communication Services
        // "T", "VZ", "TMUS", "CHTR", "CMCSA", "TWTR",
        // "SNAP", "PINS", "MTCH", "ROKU", "SPOT", "ZM", "DOCU", "WORK", "TEAM", "PTON",

        // // Growth & Emerging Stocks
        // "SHOP", "SQ", "UBER", "LYFT", "ABNB", "COIN", "HOOD", "PLTR", "SNOW", "UNITY",
        // "RBLX", "ZI", "CPNG", "BABA", "JD", "PDD", "BIDU", "BILI", "NIO", "XPEV",
        // "LI", "RIVN", "LCID", "CCIV", "SPCE", "ARKK", "ARKG", "ARKQ", "ARKW", "PRNT"
    ],

    // Indian Stocks - Top 250 by market cap and trading volume
    IN: [
        "360ONE.NS",
        "3MINDIA.NS",
        "ABB.NS",
        "ACC.NS",
        "ACMESOLAR.NS",
        "AIAENG.NS",
        "APLAPOLLO.NS",
        "AUBANK.NS",
        "AWL.NS",
        "AADHARHFC.NS",
        "AARTIIND.NS",
        "AAVAS.NS",
        "ABBOTINDIA.NS",
        "ACE.NS",
        "ADANIENSOL.NS",
        "ADANIENT.NS",
        "ADANIGREEN.NS",
        "ADANIPORTS.NS",
        "ADANIPOWER.NS",
        "ATGL.NS",
        "ABCAPITAL.NS",
        "ABFRL.NS",
        "ABREL.NS",
        "ABSLAMC.NS",
        "AEGISLOG.NS",
        "AFCONS.NS",
        "AFFLE.NS",
        "AJANTPHARM.NS",
        "AKUMS.NS",
        "APLLTD.NS",
        "ALIVUS.NS",
        "ALKEM.NS",
        "ALKYLAMINE.NS",
        "ALOKINDS.NS",
        "ARE&M.NS",
        "AMBER.NS",
        "AMBUJACEM.NS",
        "ANANDRATHI.NS",
        "ANANTRAJ.NS",
        "ANGELONE.NS",
        "APARINDS.NS",
        "APOLLOHOSP.NS",
        "APOLLOTYRE.NS",
        "APTUS.NS",
        "ASAHIINDIA.NS",
        "ASHOKLEY.NS",
        "ASIANPAINT.NS",
        "ASTERDM.NS",
        "ASTRAZEN.NS",
        "ASTRAL.NS",
        "ATUL.NS",
        "AUROFIN.NS",
        "AXISBANK.NS",
        "BASF.NS",
        "BATAINDIA.NS",
        "BEL.NS",
        "BERGEPAINT.NS",
        "BDL.NS",
        "BLS.NS",
        "BSE.NS",
        "BAJAJ-AUTO.NS",
        "BAJAJFINSV.NS",
        "BAJFINANCE.NS",
        "BALKRISIND.NS",
        "BALRAMCHIN.NS",
        "BANDHANBNK.NS",
        "BANKBARODA.NS",
        "BANKINDIA.NS",
        "MAHABANK.NS",
        "CENTRALBK.NS",
        "CANBK.NS",
        "BHARATFORG.NS",
        "BHEL.NS",
        "BPCL.NS",
        "BHARTIARTL.NS",
        "BIOCON.NS",
        "BIRLACORPN.NS",
        "BSOFT.NS",
        "BLUEDART.NS",
        "BLUESTARCO.NS",
        "BBTC.NS",
        "BOSCHLTD.NS",
        "BRITANNIA.NS",
        "CCL.NS",
        "CESC.NS",
        "CGPOWER.NS",
        "CIPLA.NS",
        "CUB.NS",
        "COALINDIA.NS",
        "COCHINSHIP.NS",
        "CADILAHC.NS",
        "CHOLAFIN.NS",
        "CROMPTON.NS",
        "CUMMINSIND.NS",
        "DABUR.NS",
        "DALBHARAT.NS",
        "DEEPAKNTR.NS",
        "DIVISLAB.NS",
        "DIXON.NS",
        "LALPATHLAB.NS",
        "DRREDDY.NS",
        "EIDPARRY.NS",
        "EIHOTEL.NS",
        "EPL.NS",
        "EICHERMOT.NS",
        "ESCORTS.NS",
        "EXIDEIND.NS",
        "FDC.NS",
        "NYKAA.NS",
        "FEDERALBNK.NS",
        "FORTIS.NS",
        "GAIL.NS",
        "GLENMARK.NS",
        "GMRINFRA.NS",
        "GODREJCP.NS",
        "GODREJPROP.NS",
        "GRANULES.NS",
        "GRASIM.NS",
        "GSPL.NS",
        "HEG.NS",
        "HCLTECH.NS",
        "HDFCAMC.NS",
        "HDFCBANK.NS",
        "HDFCLIFE.NS",
        "HAVELLS.NS",
        "HEROMOTOCO.NS",
        "HEXAWARE.NS",
        "HINDALCO.NS",
        "HINDCOPPER.NS",
        "HINDPETRO.NS",
        "HINDUNILVR.NS",
        "HINDZINC.NS",
        "POWERINDIA.NS",
        "HONAUT.NS",
        "HUDCO.NS",
        "ICICIBANK.NS",
        "ICICIGI.NS",
        "ICICIPRULI.NS",
        "IDFCFIRSTB.NS",
        "IEX.NS",
        "INDHOTEL.NS",
        "IOC.NS",
        "IOB.NS",
        "IRCTC.NS",
        "ITC.NS",
        "ITI.NS",
        "INDIACEM.NS",
        "INDIANB.NS",
        "INDIAMART.NS",
        "INDIGO.NS",
        "INDUSINDBK.NS",
        "INDUSTOWER.NS",
        "INFY.NS",
        "INGERRAND.NS",
        "INOXLEISUR.NS",
        "INTELLECT.NS",
        "ISEC.NS",
        "IPCALAB.NS",
        "JKCEMENT.NS",
        "JKLAKSHMI.NS",
        "JMFINANCIL.NS",
        "JSWSTEEL.NS",
        "JINDALSTEL.NS",
        "JUBLFOOD.NS",
        "JUBILANT.NS",
        "JUSTDIAL.NS",
        "JYOTHYLAB.NS",
        "KPITTECH.NS",
        "KEI.NS",
        "KNRCON.NS",
        "KPITTECH.NS",
        "KRBL.NS",
        "L&TFH.NS",
        "LAXMIMACH.NS",
        "LICHSGFIN.NS",
        "LTIM.NS",
        "LTTS.NS",
        "LAURUSLABS.NS",
        "LEMONTREE.NS",
        "LT.NS",
        "LUPIN.NS",
        "MRF.NS",
        "LSC.NS",
        "MARICO.NS",
        "MARUTI.NS",
        "MFSL.NS",
        "MAXHEALTH.NS",
        "MAZDOCK.NS",
        "METROPOLIS.NS",
        "MINDACORP.NS",
        "MINDTREE.NS",
        "MPHASIS.NS",
        "MCX.NS",
        "MUTHOOTFIN.NS",
        "NATIONALUM.NS",
        "NBCC.NS",
        "NCC.NS",
        "NEOGEN.NS",
        "NESTLEIND.NS",
        "NETWORK18.NS",
        "NMDC.NS",
        "NTPC.NS",
        "NAVINFLUOR.NS",
        "NAZARA.NS",
        "NIACL.NS",
        "NIITLTD.NS",
        "NLCINDIA.NS",
        "NOCIL.NS",
        "NUVOCO.NS",
        "OBEROIRLTY.NS",
        "OFSS.NS",
        "ONGC.NS",
        "OIL.NS",
        "PAYTM.NS",
        "PAGEIND.NS",
        "PERSISTENT.NS",
        "PETRONET.NS",
        "PFIZER.NS",
        "PIDILITIND.NS",
        "PEL.NS",
        "POLYCAB.NS",
        "POLYMED.NS",
        "POONAWALLA.NS",
        "PFC.NS",
        "POWERGRID.NS",
        "PRAJIND.NS",
        "PRESTIGE.NS",
        "PGHH.NS",
        "PURVA.NS",
        "QUESS.NS",
        "RBLBANK.NS",
        "RECLTD.NS",
        "RELIANCE.NS",
        "ROUTE.NS",
        "RPOWER.NS",
        "RVNL.NS",
        "SAIL.NS",
        "SBICARD.NS",
        "SBILIFE.NS",
        "SBIN.NS",
        "SHREECEM.NS",
        "SHRIRAMFIN.NS",
        "SIEMENS.NS",
        "SRF.NS",
        "MOTHERSON.NS",
        "SOLARINDS.NS",
        "SONACOMS.NS",
        "SOUTHBANK.NS",
        "STARHEALTH.NS",
        "SUNTV.NS",
        "SYNGENE.NS",
        "TVSMOTOR.NS",
        "TMB.NS",
        "TANLA.NS",
        "TATACOMM.NS",
        "TATACONSUM.NS",
        "TATAMOTORS.NS",
        "TATAPOWER.NS",
        "TATASTEEL.NS",
        "TCS.NS",
        "TECHM.NS",
        "RAMCOCEM.NS",
        "THERMAX.NS",
        "THYROCARE.NS",
        "TIINDIA.NS",
        "TITAN.NS",
        "TORNTPHARM.NS",
        "TORNTPOWER.NS",
        "TRENT.NS",
        "TRIDENT.NS",
        "TRIVENI.NS",
        "UJJIVAN.NS",
        "ULTRACEMCO.NS",
        "UPL.NS",
        "UTIAMC.NS",
        "VOLTAS.NS",
        "WIPRO.NS",
        "WOCKPHARMA.NS",
        "YESBANK.NS",
        "ZEEL.NS",
        "ZENSARTECH.NS",
        "ZENTEC.NS",
        "ZENSARTECH.NS",
        "ZYDUSLIFE.NS",
        "ECLERX.NS"
    ]
} as const;

export type MarketType = 'US' | 'IN';
export type StockSymbol = string;

/**
 * Function to get all 500 stocks as a flat array
 */
export const getAllStocks = (): StockSymbol[] => {
    return [...TOP_500_STOCKS.US, ...TOP_500_STOCKS.IN];
};

/**
 * Function to get stocks by market
 */
export const getStocksByMarket = (market: MarketType): readonly StockSymbol[] => {
    if (market === 'US') return TOP_500_STOCKS.US;
    if (market === 'IN') return TOP_500_STOCKS.IN;
    return getAllStocks();
};

/**
 * Function to get a batch of stocks (for processing in chunks)
 */
export const getStockBatch = (batchSize: number = 50, batchNumber: number = 0): StockSymbol[] => {
    const allStocks = getAllStocks();
    const startIndex = batchNumber * batchSize;
    const endIndex = Math.min(startIndex + batchSize, allStocks.length);
    return allStocks.slice(startIndex, endIndex);
};

// CommonJS compatibility
module.exports = {
    TOP_500_STOCKS,
    getAllStocks,
    getStocksByMarket,
    getStockBatch
};
